### ISSUE TITLE
Retry on failure 

### ISSUE THREAD

**Issue by NightMachinery** [sodiumjoe/tlrl#4]
Currently I sometimes get this error:
Error: ErrorMessage { msg: "Error deserializing mercury api response json: EOF while parsing a value at line 1 column 0" }

**Comment by sodiumjoe** [comment]
@NightMachinary thanks for the issue! I get that sometimes too, and you're right, a retry would be a good idea. I should have some time to add this in the next couple weeks.

**Comment by NightMachinery** [comment]
I actually ended up using this shell function:

retry () {
until "$@"
do
echo Retrying \'"$*"\' "..." >&2
sleep 1
done
}

It works beautifully. Perhaps just adding it to the help is enough, since
this is a generic solution that works with a lot of binaries.
