### ISSUE TITLE
Mercury API has shut down

### ISSUE THREAD

**Issue by sodiumjoe** [sodiumjoe/tlrl#8]
My plan is to port the mercury parser code to rust and include the parser in this project. Not sure when I'll be able to get around to that though.

**Comment by NightMachinery** [comment]
How can I tell tlrl to use an instance of Mercury that I’m running locally?

PS: I think this actually is preferable to porting Mercury to Rust. Web changes fast and things need to be maintained. At best, this would a fork that splits the community and resources; More likely, the Rust port would be in a constant state of catching up.

**Comment by sodiumjoe** [comment]
To change the mercury instance, just change this line: https://github.com/sodiumjoe/tlrl/blob/master/src/parser.rs#L17

This project is really a way for me to learn rust, so porting mercury to rust makes sense for me, but another viable option is to bundle mercury into the rust binary and call out to it for parsing.

It might be feasible to make it a config option. Either way, I'm not sure when I'll be able to get around to it.

**Comment by NightMachinery** [comment]
I fixed this by using the local CLI interface of mercury-parser https://github.com/NightMachinary/tlrl/commit/d000610668f21a3453f9106ca5e7a61d5ce2bb80.

**Comment by sodiumjoe** [comment]
@NightMachinary :wave: Sorry for the slow response! I took a look at your commit, and it looks fine to me. If you can clean it up and make a PR, I'd be happy to merge. I'd be happy to take the prefix thing, too, but please make it a separate PR.

Clean up here would be to remove the mercury stuff from config, and delete the commented out stuff. If you don't want to do this, I'd be happy to do it myself, but wanted to give you a chance so you can get credit as a contributor.

I also took a look at trying to incorporate the mercury-parser node project as a bundled binary, like https://github.com/dflemstr/rq does with lodash, but that actually looks like it'll be really hard and annoying.

I think I would still like to port the mercury-parser logic to rust, but, to your point I think I'll try to leave an option to use a local install of mercury-parser if available.

**Comment by NightMachinery** [comment]
@sodiumjoe I’d be happy to clean it up, but I don’t know how to get the PRs separate for the two changes? Should I delete the prefix code, commit, then add the code again and commit? That seems pointless?

**Comment by sodiumjoe** [comment]
you can either do that or `git rebase -i` and create separate commits, or `git reset` to master and `git add -p` to stage the appropriate patches.

The resulting code will be the same, but the git history will reflect atomic commits with just the relevant changes in each commit, which is not pointless.

If it seems like too much of a hassle, don't worry about, I'll do it, and I think I can still keep you as a contributor in git.

**Comment by NightMachinery** [comment]
I’m not proficient with git, but I’ll play around, I think I’ll manage. :)

**Comment by sodiumjoe** [comment]
fixed by https://github.com/sodiumjoe/tlrl/pull/9
